name: Build with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        java: ['17', '21']

    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: "${{github.run_number}}"
      MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --no-transfer-progress"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and Test with Maven
        run: ./mvnw $MAVEN_CLI_OPTS clean verify 
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: ${{ always() && matrix.java == '17' }} 
        with:
          name: test-results
          path: '**/target/surefire-reports/TEST-*.xml'
      - name: Test Stache Javadoc 
        run: cd test/jstachio-test-stache && ../../mvnw $MAVEN_CLI_OPTS clean verify -Pstache-javadoc
      - name: Test Gradle Support
        run: cd test/jstachio-test-gradle && ./gradlew --console=plain --no-daemon --no-build-cache clean build 
